version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - node -v
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
